### ISSUE TITLE
hi, how can I retrain the CoPM? I can find the training manuscript and the dataset.

### ISSUE THREAD

**Issue by hankerbit** [BIT-MCS/Cadre#4]

**Comment by nuomizai** [comment]
Sorry for the trouble. We could not upload the training datasets of CoPM because they exceed Google Drive's storage capacity. However, we provide [a sample dataset](https://drive.google.com/file/d/148e3jbWkJn-m68MjDVGD5a88IVLHfHcm/view?usp=sharing), and you can use it to try running the training code for CoPM with the script `/scripts/train_encoder.sh`. 

We could also provide the very original code we used for collecting the datasets. You can find them under `/statics` (i.e., the [vae_agent.py](https://github.com/BIT-MCS/Cadre/blob/main/statics/vae_agent.py) and the [base_vae_agent.py](https://github.com/BIT-MCS/Cadre/blob/main/statics/base_vae_agent.py).

**Comment by hankerbit** [comment]
Thanks very much, I find them.
 Nice work!!
